// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:1cce51d6-7003-4685-84b3-6fe938ea0fe4",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_0MfJDWqhg",
    "aws_user_pools_web_client_id": "1eegfok8be84a27r5v8jip3j84",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://r6ewmk2gtvfnjhp7vtfa4wih7a.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
